"""Mastery dashboard aggregation for Lesson Mode (Increment 11).

Purely a read-side view over data other Lesson Mode services already
persist -- nothing here is generated by a model or written to Firestore.
It aggregates, per user, across every lesson they've touched:

- vocabulary mastery (from `UserCardProgress.leitner_box` distribution --
  box 1 = learning, box 2 = developing, box 3 = mastered; the same Leitner
  state `services/flashcard_review.py` already maintains)
- quiz and open-response scores (from `QuizAttempt` / `OpenResponseAttempt`)
- debate skill feedback (from `DebateReflection`, Increment 10's
  educational judge analysis)
- a single, deterministic, rule-based "recommended next activity"

Deliberately does NOT combine any of these into one overall score. Quiz
accuracy, vocabulary mastery, and debate feedback measure different things
and are shown separately; `DebateSkillSummary.is_estimate` is always True
and is meant to be surfaced to the student as "AI estimate, not a precise
measurement" -- the debate rubric is inherently more subjective than a
multiple-choice quiz score, and presenting it with the same certainty
would be misleading.
"""

import logging
from collections import defaultdict
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from models.lesson_models import Lesson, QuizAttempt, OpenResponseAttempt
from services.flashcard_review import is_card_due
from services.lesson_repository import LessonRepository

logger = logging.getLogger(__name__)

# Below this, a lesson's most recent quiz score is treated as "could use a
# retake" for the recommendation engine. Not used for anything else --
# never blended into a mastery percentage or a pass/fail label.
QUIZ_RETAKE_THRESHOLD = 70.0

# How many recent quiz/open-response attempts (across all lessons) to
# surface in the dashboard, and how many recent debate-reflection skills to
# show as a "profile" without collapsing them into one number.
RECENT_ITEMS_LIMIT = 5
RECENT_SKILLS_LIMIT = 3


class VocabularyMasterySummary(BaseModel):
    """Leitner-box based vocabulary mastery for one lesson. `mastery_percent`
    is deliberately just "box-3 cards / total cards" -- a plain, explainable
    ratio, not a weighted or smoothed score."""

    total_cards: int
    mastery_percent: float = Field(ge=0, le=100)
    box_distribution: Dict[str, int]  # {"1": learning, "2": developing, "3": mastered}
    cards_due: int


class QuizScoreEntry(BaseModel):
    lesson_id: str
    lesson_title: str
    score: float
    created_at: str


class OpenResponseScoreEntry(BaseModel):
    lesson_id: str
    lesson_title: str
    score: int
    created_at: str


class LessonMasterySummary(BaseModel):
    """Per-bill progress -- one of these per lesson the user has touched."""

    lesson_id: str
    lesson_title: str
    completed: bool
    has_quiz: bool
    has_open_response: bool
    vocabulary: VocabularyMasterySummary
    quiz_attempts: int
    best_quiz_score: Optional[float] = None
    latest_quiz_score: Optional[float] = None
    open_response_attempts: int
    latest_open_response_score: Optional[int] = None


class DebateSkillSummary(BaseModel):
    """A "profile" built from recent post-debate reflections (Increment 10)
    -- never a single blended number. `is_estimate` is always True: this
    reflects an LLM's qualitative read of one transcript, not a measured
    quantity, and the frontend must label it accordingly."""

    reflections_count: int
    most_recent_recommended_skill: Optional[str] = None
    most_recent_recommended_activity: Optional[str] = None
    most_recent_view_changed: Optional[str] = None
    recent_recommended_skills: List[str] = Field(default_factory=list)
    is_estimate: bool = True


ActivityType = Literal[
    "generate_lesson", "review_flashcards", "take_quiz",
    "open_response", "retake_quiz", "debate_and_reflect", "explore_new_bill",
]


class RecommendedActivity(BaseModel):
    label: str
    reason: str
    activity_type: ActivityType
    lesson_id: Optional[str] = None


class MasteryDashboard(BaseModel):
    has_activity: bool
    total_lessons_started: int
    completed_lesson_count: int
    overall_vocabulary_mastery_percent: float = Field(ge=0, le=100)
    overall_cards_due: int
    lessons: List[LessonMasterySummary]
    recent_quiz_scores: List[QuizScoreEntry]
    recent_open_response_scores: List[OpenResponseScoreEntry]
    debate_skill: Optional[DebateSkillSummary] = None
    recommended_activity: RecommendedActivity


def _empty_dashboard() -> MasteryDashboard:
    return MasteryDashboard(
        has_activity=False,
        total_lessons_started=0,
        completed_lesson_count=0,
        overall_vocabulary_mastery_percent=0.0,
        overall_cards_due=0,
        lessons=[],
        recent_quiz_scores=[],
        recent_open_response_scores=[],
        debate_skill=None,
        recommended_activity=RecommendedActivity(
            label="Generate your first lesson",
            reason="You haven't started a Lesson Mode activity yet.",
            activity_type="generate_lesson",
        ),
    )


class MasteryDashboardService:
    def __init__(self, repository: Optional[LessonRepository] = None):
        self._repository = repository or LessonRepository()

    def _vocabulary_summary(self, user_id: str, lesson: Lesson) -> VocabularyMasterySummary:
        total = len(lesson.vocabulary_card_ids)
        if total == 0:
            return VocabularyMasterySummary(
                total_cards=0, mastery_percent=0.0, box_distribution={"1": 0, "2": 0, "3": 0}, cards_due=0
            )

        # Deliberately does NOT call FlashcardReviewService.get_review_state:
        # that method side-effect-initializes a LessonProgress record on
        # first call, which would be a write triggered by a read-only
        # dashboard fetch. A lesson with no LessonProgress record yet
        # genuinely has no UserCardProgress rows either (both are only ever
        # created together, by review actions), so every card is untouched
        # (box 1, due) without needing that side effect.
        progress = self._repository.get_lesson_progress(user_id, lesson.lesson_id)
        session = progress.current_session if progress else 0

        box_distribution = {"1": 0, "2": 0, "3": 0}
        due = 0
        mastered = 0
        for card_id in lesson.vocabulary_card_ids:
            card_progress = self._repository.get_user_card_progress(user_id, card_id)
            box = card_progress.leitner_box if card_progress else 1
            box_distribution[str(box)] += 1
            if box == 3:
                mastered += 1
            if is_card_due(card_progress, session):
                due += 1

        return VocabularyMasterySummary(
            total_cards=total,
            mastery_percent=round(100 * mastered / total, 1),
            box_distribution=box_distribution,
            cards_due=due,
        )

    def _recommend_activity(
        self, lessons: List[LessonMasterySummary], lessons_with_reflection: set
    ) -> RecommendedActivity:
        """Deterministic, rule-based priority -- never a second AI call.
        Exactly one recommendation is returned so the frontend always has
        one prominent next step, and it's always reproducible from the same
        data (no model variance to explain to a student)."""
        due_lessons = sorted(
            (l for l in lessons if l.vocabulary.cards_due > 0),
            key=lambda l: l.vocabulary.cards_due,
            reverse=True,
        )
        if due_lessons:
            l = due_lessons[0]
            return RecommendedActivity(
                label=f'Review {l.vocabulary.cards_due} due flashcard(s) in "{l.lesson_title}"',
                reason="Spaced-repetition cards are ready for review.",
                activity_type="review_flashcards",
                lesson_id=l.lesson_id,
            )

        for l in lessons:
            if l.has_quiz and l.quiz_attempts == 0:
                return RecommendedActivity(
                    label=f'Take the quiz for "{l.lesson_title}"',
                    reason="You haven't attempted this lesson's quiz yet.",
                    activity_type="take_quiz",
                    lesson_id=l.lesson_id,
                )

        for l in lessons:
            if l.has_open_response and l.open_response_attempts == 0:
                return RecommendedActivity(
                    label=f'Answer the open-response question for "{l.lesson_title}"',
                    reason="You haven't answered this lesson's open-response question yet.",
                    activity_type="open_response",
                    lesson_id=l.lesson_id,
                )

        for l in lessons:
            if l.latest_quiz_score is not None and l.latest_quiz_score < QUIZ_RETAKE_THRESHOLD:
                return RecommendedActivity(
                    label=f'Retake the quiz for "{l.lesson_title}"',
                    reason=f"Your last score was {l.latest_quiz_score:.0f}%.",
                    activity_type="retake_quiz",
                    lesson_id=l.lesson_id,
                )

        for l in lessons:
            if l.completed and l.lesson_id not in lessons_with_reflection:
                return RecommendedActivity(
                    label=f'Debate "{l.lesson_title}" and reflect on it afterward',
                    reason="You've completed this lesson's quiz and open-response question.",
                    activity_type="debate_and_reflect",
                    lesson_id=l.lesson_id,
                )

        return RecommendedActivity(
            label="Explore a new bill",
            reason="You're caught up on every lesson you've started.",
            activity_type="explore_new_bill",
        )

    def get_dashboard(self, user_id: str) -> MasteryDashboard:
        quiz_attempts = self._repository.list_quiz_attempts(user_id)
        open_response_attempts = self._repository.list_open_response_attempts(user_id)
        lesson_progress_records = self._repository.list_lesson_progress_for_user(user_id)
        reflections = self._repository.list_debate_reflections(user_id)

        touched_lesson_ids = set()
        touched_lesson_ids.update(a.lesson_id for a in quiz_attempts)
        touched_lesson_ids.update(a.lesson_id for a in open_response_attempts)
        touched_lesson_ids.update(p.lesson_id for p in lesson_progress_records)
        touched_lesson_ids.update(r.lesson_id for r in reflections)

        if not touched_lesson_ids:
            return _empty_dashboard()

        quiz_by_lesson: Dict[str, List[QuizAttempt]] = defaultdict(list)
        for a in quiz_attempts:
            quiz_by_lesson[a.lesson_id].append(a)
        open_response_by_lesson: Dict[str, List[OpenResponseAttempt]] = defaultdict(list)
        for a in open_response_attempts:
            open_response_by_lesson[a.lesson_id].append(a)
        lessons_with_reflection = {r.lesson_id for r in reflections}

        lessons_summary: List[LessonMasterySummary] = []
        recent_quiz_entries: List[QuizScoreEntry] = []
        recent_open_response_entries: List[OpenResponseScoreEntry] = []
        total_cards_all = 0
        mastered_cards_all = 0
        cards_due_all = 0
        completed_count = 0

        for lesson_id in sorted(touched_lesson_ids):
            lesson = self._repository.get_lesson(lesson_id)
            if lesson is None:
                # Defensive: never let one stale/missing lesson break the
                # whole dashboard for every other lesson the user has.
                logger.warning("mastery_dashboard lesson_id=%s not found, skipping", lesson_id)
                continue

            vocab = self._vocabulary_summary(user_id, lesson)
            total_cards_all += vocab.total_cards
            mastered_cards_all += round(vocab.mastery_percent / 100 * vocab.total_cards) if vocab.total_cards else 0
            cards_due_all += vocab.cards_due

            lesson_quiz_attempts = sorted(quiz_by_lesson.get(lesson_id, []), key=lambda a: a.created_at)
            lesson_or_attempts = sorted(open_response_by_lesson.get(lesson_id, []), key=lambda a: a.created_at)

            has_quiz = bool(lesson.quiz_question_ids)
            has_open_response = bool(lesson.open_response_question_id)
            completed = (
                (has_quiz or has_open_response)
                and (not has_quiz or len(lesson_quiz_attempts) > 0)
                and (not has_open_response or len(lesson_or_attempts) > 0)
            )
            if completed:
                completed_count += 1

            lessons_summary.append(LessonMasterySummary(
                lesson_id=lesson_id,
                lesson_title=lesson.lesson_title,
                completed=completed,
                has_quiz=has_quiz,
                has_open_response=has_open_response,
                vocabulary=vocab,
                quiz_attempts=len(lesson_quiz_attempts),
                best_quiz_score=max((a.score for a in lesson_quiz_attempts), default=None),
                latest_quiz_score=lesson_quiz_attempts[-1].score if lesson_quiz_attempts else None,
                open_response_attempts=len(lesson_or_attempts),
                latest_open_response_score=lesson_or_attempts[-1].score if lesson_or_attempts else None,
            ))

            for a in lesson_quiz_attempts:
                recent_quiz_entries.append(QuizScoreEntry(
                    lesson_id=lesson_id, lesson_title=lesson.lesson_title,
                    score=a.score, created_at=a.created_at.isoformat(),
                ))
            for a in lesson_or_attempts:
                recent_open_response_entries.append(OpenResponseScoreEntry(
                    lesson_id=lesson_id, lesson_title=lesson.lesson_title,
                    score=a.score, created_at=a.created_at.isoformat(),
                ))

        recent_quiz_entries.sort(key=lambda e: e.created_at, reverse=True)
        recent_open_response_entries.sort(key=lambda e: e.created_at, reverse=True)

        overall_vocab_pct = (
            round(100 * mastered_cards_all / total_cards_all, 1) if total_cards_all else 0.0
        )

        debate_skill = None
        if reflections:
            recent_reflections = sorted(reflections, key=lambda r: r.created_at, reverse=True)
            most_recent = recent_reflections[0]
            debate_skill = DebateSkillSummary(
                reflections_count=len(reflections),
                most_recent_recommended_skill=most_recent.recommended_skill,
                most_recent_recommended_activity=most_recent.recommended_next_activity,
                most_recent_view_changed=most_recent.view_changed,
                recent_recommended_skills=[r.recommended_skill for r in recent_reflections[:RECENT_SKILLS_LIMIT]],
            )

        return MasteryDashboard(
            has_activity=True,
            total_lessons_started=len(lessons_summary),
            completed_lesson_count=completed_count,
            overall_vocabulary_mastery_percent=overall_vocab_pct,
            overall_cards_due=cards_due_all,
            lessons=lessons_summary,
            recent_quiz_scores=recent_quiz_entries[:RECENT_ITEMS_LIMIT],
            recent_open_response_scores=recent_open_response_entries[:RECENT_ITEMS_LIMIT],
            debate_skill=debate_skill,
            recommended_activity=self._recommend_activity(lessons_summary, lessons_with_reflection),
        )
