"""Grounded multiple-choice quiz generation for Lesson Mode (Increment 5).

Unlike lesson/vocabulary generation, quiz *facts* (the correct answers) are
never invented by a model call here -- they're pulled directly from data
that Increments 2/3 already generated and grounded against real bill
sections: `Lesson.major_provisions`/`stakeholders` (`GroundedClaim`s) and
the lesson's `Flashcard` vocabulary definitions. A model call is used only
to phrase a natural question stem + explanation for each fact (never to
invent the correct answer itself), which keeps "the correct answer is
supported by the cited section" true by construction rather than something
that needs re-validating here.

Distractor pipeline (the part that *is* novel to this module):
1. Embedding similarity: rank every other fact in the same lesson by
   similarity to the correct answer, keep the top plausible ones.
2. Reject candidates too similar to the correct answer (could reasonably
   be considered correct too) and exact/case-insensitive duplicates.
3. If fewer than 3 valid distractors survive, fall back to one constrained
   model call asking for the remainder, validated the same way.
4. If still short, the question is dropped rather than shipped with fewer
   than 4 answer choices.
"""

import logging
import random
import re
from dataclasses import dataclass
from typing import List, Optional, Set, Tuple

from pydantic import BaseModel, Field, ValidationError

from models.lesson_models import Flashcard, Lesson, QuizQuestion
from services.json_utils import extract_json_object
from services.lesson_generation import DEFAULT_LESSON_MODEL, LLMCallable, _default_llm_call
from services.lesson_repository import LessonRepository
from services.rag.embeddings import get_embedding_provider

logger = logging.getLogger(__name__)

MIN_QUESTIONS = 5
MAX_QUESTIONS = 8
NUM_DISTRACTORS = 3
NUM_ANSWER_CHOICES = NUM_DISTRACTORS + 1

# A distractor scoring at or above this cosine similarity to the correct
# answer is rejected as "could reasonably be considered correct too."
MAX_DISTRACTOR_SIMILARITY = 0.92

_VALID_DIFFICULTIES = {"beginner", "intermediate", "advanced"}
_IMPLEMENTATION_KEYWORDS = re.compile(
    r"\b(implement|regulation|enforce|effective date|shall issue|carry out|"
    r"administer|enactment|agency|department|secretary)\b",
    re.IGNORECASE,
)

PHRASING_SYSTEM_PROMPT = """You are writing multiple-choice question stems for a high-school civic-education quiz about a bill.

For each provided fact, write ONE clear question whose correct answer is exactly that fact's
text as given -- do not paraphrase the fact, since it will be used verbatim as the correct
answer choice. Also write a one-to-two sentence explanation of why that answer is correct,
referencing the bill. Assign a difficulty (beginner, intermediate, or advanced) based on how
much bill-specific knowledge is needed to answer correctly.

Do not introduce facts that are not present in what's given.
Return only structured JSON."""

_PHRASING_JSON_SCHEMA_INSTRUCTIONS = """Return ONLY a single JSON object (no markdown fences, no commentary) with exactly this shape:

{
  "questions": [
    {"fact_index": 0, "question": "string", "explanation": "string", "difficulty": "beginner" | "intermediate" | "advanced"},
    ...
  ]
}

Include exactly one entry per fact_index provided below, using the fact_index values given."""

DISTRACTOR_FALLBACK_SYSTEM_PROMPT = """Create plausible but incorrect answer choices for the question.

Constraints:
- Each distractor must be clearly incorrect according to the provided lesson.
- Each distractor should sound realistic to a student who partially understands the topic.
- Do not use jokes, nonsense, or obviously unrelated concepts.
- Do not create another answer that could reasonably be considered correct.
- Keep choices similar in length and grammatical structure.

Return only the distractor strings."""


class QuizGenerationError(Exception):
    """Raised when quiz questions cannot be produced at all (no lesson
    content, or the phrasing model's output is unparseable)."""


@dataclass
class _QuizFact:
    """A candidate correct-answer fact pulled from already-grounded lesson
    content -- never itself generated by a model call."""

    fact_id: str
    text: str
    section_ids: List[str]
    question_type: str
    context: str


class _PhrasedQuestionDraft(BaseModel):
    fact_index: int = Field(ge=0)
    question: str = Field(min_length=1)
    explanation: str = Field(min_length=1)
    difficulty: str = Field(default="intermediate")


class _PhrasingDraft(BaseModel):
    questions: List[_PhrasedQuestionDraft] = Field(default_factory=list)


def _normalize_difficulty(raw_difficulty: str) -> str:
    normalized = raw_difficulty.strip().lower()
    return normalized if normalized in _VALID_DIFFICULTIES else "intermediate"


def _classify_provision_type(claim_text: str) -> str:
    """Heuristically split `major_provisions` claims into "implementation"
    facts (how/who carries out the bill) vs. general "provision" facts, so
    quizzes can draw from both categories without a separate LLM call."""
    return "implementation" if _IMPLEMENTATION_KEYWORDS.search(claim_text) else "provision"


def build_fact_pool(lesson: Lesson, flashcards: List[Flashcard]) -> List[_QuizFact]:
    facts: List[_QuizFact] = []

    for card in flashcards:
        facts.append(
            _QuizFact(
                fact_id=f"vocab:{card.card_id}",
                text=card.simple_definition,
                section_ids=[card.section_id],
                question_type="vocabulary",
                context=f'the term "{card.term}"',
            )
        )

    for i, claim in enumerate(lesson.stakeholders):
        facts.append(
            _QuizFact(
                fact_id=f"stakeholder:{i}",
                text=claim.claim,
                section_ids=claim.section_ids,
                question_type="stakeholder_impact",
                context="a stakeholder impact of this bill",
            )
        )

    for i, claim in enumerate(lesson.major_provisions):
        qtype = _classify_provision_type(claim.claim)
        facts.append(
            _QuizFact(
                fact_id=f"provision:{i}",
                text=claim.claim,
                section_ids=claim.section_ids,
                question_type=qtype,
                context=(
                    "how this bill is implemented" if qtype == "implementation"
                    else "a provision of this bill"
                ),
            )
        )

    return facts


def select_target_facts(facts: List[_QuizFact], target_count: int) -> List[_QuizFact]:
    """Round-robin across question_types so the final quiz draws from
    multiple categories rather than exhausting one type first."""
    by_type: dict = {}
    for f in facts:
        by_type.setdefault(f.question_type, []).append(f)

    order = ["vocabulary", "stakeholder_impact", "provision", "implementation"]
    cursors = {t: 0 for t in order}
    selected: List[_QuizFact] = []

    while len(selected) < target_count:
        progressed = False
        for t in order:
            bucket = by_type.get(t, [])
            i = cursors[t]
            if i < len(bucket):
                selected.append(bucket[i])
                cursors[t] += 1
                progressed = True
                if len(selected) >= target_count:
                    break
        if not progressed:
            break

    return selected


def _build_phrasing_prompt(facts: List[_QuizFact]) -> str:
    fact_blocks = "\n\n".join(
        f'[fact_index {i}] ({f.question_type}, about {f.context})\n"{f.text}"'
        for i, f in enumerate(facts)
    )
    return f"Facts to write questions for:\n\n{fact_blocks}\n\n{_PHRASING_JSON_SCHEMA_INSTRUCTIONS}"


def ground_phrasing(raw_text: str, num_facts: int) -> List[_PhrasedQuestionDraft]:
    """Parse the phrasing model's JSON. Entries with an out-of-range or
    duplicate fact_index are dropped (not fatal); a totally unparseable
    response raises `QuizGenerationError` so the caller can decide whether
    to reject the batch."""
    try:
        data = extract_json_object(raw_text)
        draft = _PhrasingDraft.model_validate(data)
    except (ValidationError, ValueError) as e:
        raise QuizGenerationError(f"Model output failed schema validation: {e}") from e

    seen_indices: Set[int] = set()
    valid: List[_PhrasedQuestionDraft] = []
    for item in draft.questions:
        if not (0 <= item.fact_index < num_facts):
            continue
        if item.fact_index in seen_indices:
            continue
        seen_indices.add(item.fact_index)
        valid.append(item)
    return valid


def _cosine_similarities(query_vec: List[float], vectors: List[List[float]]) -> List[float]:
    import numpy as np

    query = np.array(query_vec, dtype=float)
    matrix = np.array(vectors, dtype=float)
    query_norm = np.linalg.norm(query)
    if query_norm == 0:
        return [0.0] * len(vectors)
    matrix_norms = np.linalg.norm(matrix, axis=1)
    scores = np.zeros(len(vectors))
    nonzero = matrix_norms != 0
    scores[nonzero] = (matrix[nonzero] @ query) / (matrix_norms[nonzero] * query_norm)
    return scores.tolist()


def rank_candidates_by_similarity(
    correct_answer: str, candidates: List[str]
) -> List[Tuple[str, float]]:
    """Rank `candidates` by embedding-similarity to `correct_answer`,
    most-similar first. Empty input returns an empty ranking."""
    if not candidates:
        return []
    provider = get_embedding_provider()
    texts = [correct_answer] + candidates
    provider.fit(texts)
    vectors = provider.embed_batch(texts)
    scores = _cosine_similarities(vectors[0], vectors[1:])
    return sorted(zip(candidates, scores), key=lambda pair: pair[1], reverse=True)


def select_embedding_distractors(
    correct_answer: str, candidate_pool: List[str], num_needed: int
) -> List[str]:
    """Pick up to `num_needed` distractors from `candidate_pool`, ranked by
    similarity to `correct_answer`, excluding duplicates and anything too
    similar to be unambiguously wrong."""
    ranked = rank_candidates_by_similarity(correct_answer, candidate_pool)
    selected: List[str] = []
    seen_lower = {correct_answer.strip().lower()}

    for text, score in ranked:
        key = text.strip().lower()
        if key in seen_lower:
            continue
        if score >= MAX_DISTRACTOR_SIMILARITY:
            continue
        selected.append(text.strip())
        seen_lower.add(key)
        if len(selected) >= num_needed:
            break

    return selected


def _validate_fallback_distractors(
    correct_answer: str, candidates: List[str], already_selected: List[str], num_needed: int
) -> List[str]:
    ranked = rank_candidates_by_similarity(correct_answer, candidates)
    validated: List[str] = []
    seen_lower = {correct_answer.strip().lower()} | {d.strip().lower() for d in already_selected}

    for text, score in ranked:
        key = text.strip().lower()
        if key in seen_lower:
            continue
        if score >= MAX_DISTRACTOR_SIMILARITY:
            continue
        validated.append(text.strip())
        seen_lower.add(key)
        if len(validated) >= num_needed:
            break

    return validated


def _build_distractor_fallback_prompt(
    question: str, correct_answer: str, lesson_context: str, num_needed: int
) -> str:
    return (
        f"Question: {question}\n"
        f"Correct answer: {correct_answer}\n"
        f"Lesson context:\n{lesson_context}\n\n"
        f"Generate exactly {num_needed} distractor answer choices.\n\n"
        'Return ONLY a JSON object of this shape (no markdown fences, no commentary): '
        '{"distractors": ["string", ...]}'
    )


def shuffle_choices(correct_answer: str, distractors: List[str]) -> Tuple[List[str], int]:
    """Randomize answer order and report the correct answer's resulting
    index. Exposed as a standalone function so tests can exercise the
    "not always the same position" behavior directly."""
    choices = [correct_answer] + list(distractors)
    random.shuffle(choices)
    return choices, choices.index(correct_answer)


class QuizGenerationService:
    """Generates and persists a grounded multiple-choice quiz for a lesson."""

    def __init__(
        self,
        repository: Optional[LessonRepository] = None,
        llm_call: Optional[LLMCallable] = None,
    ):
        self._repository = repository or LessonRepository()
        self._llm_call = llm_call or _default_llm_call

    async def _generate_fallback_distractors(
        self, question: str, correct_answer: str, lesson_context: str, num_needed: int, model: str
    ) -> List[str]:
        prompt = _build_distractor_fallback_prompt(question, correct_answer, lesson_context, num_needed)
        try:
            raw_text = await self._llm_call(DISTRACTOR_FALLBACK_SYSTEM_PROMPT, prompt, model)
            data = extract_json_object(raw_text)
        except ValueError as e:
            logger.warning("quiz_generation fallback_distractor_parse_failed: %s", e)
            return []

        raw_candidates = data.get("distractors", [])
        candidates = [c.strip() for c in raw_candidates if isinstance(c, str) and c.strip()]
        return _validate_fallback_distractors(correct_answer, candidates, [], num_needed)

    async def _build_answer_choices(
        self,
        question: str,
        correct_answer: str,
        candidate_pool: List[str],
        lesson_context: str,
        model: str,
    ) -> Optional[Tuple[List[str], int]]:
        distractors = select_embedding_distractors(correct_answer, candidate_pool, NUM_DISTRACTORS)

        if len(distractors) < NUM_DISTRACTORS:
            needed = NUM_DISTRACTORS - len(distractors)
            fallback = await self._generate_fallback_distractors(
                question, correct_answer, lesson_context, needed, model
            )
            seen_lower = {correct_answer.strip().lower()} | {d.strip().lower() for d in distractors}
            for candidate in fallback:
                if candidate.strip().lower() in seen_lower:
                    continue
                distractors.append(candidate)
                seen_lower.add(candidate.strip().lower())
                if len(distractors) >= NUM_DISTRACTORS:
                    break

        if len(distractors) < NUM_DISTRACTORS:
            return None

        return shuffle_choices(correct_answer, distractors[:NUM_DISTRACTORS])

    async def generate_quiz(
        self,
        lesson_id: str,
        model: str = DEFAULT_LESSON_MODEL,
        min_questions: int = MIN_QUESTIONS,
        max_questions: int = MAX_QUESTIONS,
    ) -> List[QuizQuestion]:
        """Generate, ground, and persist a multiple-choice quiz for an
        already-generated lesson (`lesson_id` must exist -- quizzes are
        built from a lesson's grounded content, not raw bill text)."""
        lesson = self._repository.get_lesson(lesson_id)
        if lesson is None:
            raise QuizGenerationError(f"No lesson found for lesson_id={lesson_id!r}")

        flashcards = [
            card for card in (
                self._repository.get_flashcard(cid) for cid in lesson.vocabulary_card_ids
            ) if card is not None
        ]

        facts = build_fact_pool(lesson, flashcards)
        if not facts:
            raise QuizGenerationError(
                f"No lesson content available to generate quiz questions for lesson_id={lesson_id!r}"
            )

        target_count = min(max_questions, len(facts))
        if target_count < min_questions:
            logger.info(
                "quiz_generation fewer_than_min_facts lesson_id=%s facts=%d min=%d",
                lesson_id, len(facts), min_questions,
            )
        selected_facts = select_target_facts(facts, target_count)

        prompt = _build_phrasing_prompt(selected_facts)
        raw_text = await self._llm_call(PHRASING_SYSTEM_PROMPT, prompt, model)
        phrased = ground_phrasing(raw_text, len(selected_facts))

        all_fact_texts = [f.text for f in facts]
        context_excerpt = "\n".join(f"- {f.text}" for f in facts[:8])

        questions: List[QuizQuestion] = []
        for item in phrased:
            fact = selected_facts[item.fact_index]
            candidate_pool = [t for t in all_fact_texts if t.strip().lower() != fact.text.strip().lower()]

            built = await self._build_answer_choices(
                item.question, fact.text, candidate_pool, context_excerpt, model
            )
            if built is None:
                logger.warning(
                    "quiz_generation dropped_question insufficient_distractors fact_id=%s lesson_id=%s",
                    fact.fact_id, lesson_id,
                )
                continue

            choices, correct_index = built
            question_id = f"{lesson_id}-quiz-{len(questions) + 1}"
            questions.append(
                QuizQuestion(
                    question_id=question_id,
                    lesson_id=lesson_id,
                    question=item.question,
                    answer_choices=choices,
                    correct_answer_index=correct_index,
                    explanation=item.explanation,
                    section_ids=fact.section_ids,
                    difficulty=_normalize_difficulty(item.difficulty),
                    question_type=fact.question_type,
                )
            )

        if not questions:
            raise QuizGenerationError(
                "Could not produce any valid quiz questions -- insufficient distractors for every candidate"
            )

        for question in questions:
            self._repository.create_quiz_question(question)

        new_ids = [q.question_id for q in questions]
        merged_ids = lesson.quiz_question_ids + [i for i in new_ids if i not in lesson.quiz_question_ids]
        if merged_ids != lesson.quiz_question_ids:
            lesson = lesson.model_copy(update={"quiz_question_ids": merged_ids})
            self._repository.create_lesson(lesson)

        logger.info("quiz_generation lesson_id=%s questions=%d", lesson_id, len(questions))
        return questions
